extends:
  - standard
plugins:
  - standard
  - promise
env:
  browser: true

globals:
  define: true

rules:
  no-tabs: off
  indent:
    - error
    - tab
  semi: 
    - error
    - always
  keyword-spacing: off
  space-before-function-paren: 
    - error
    - never
  one-var: off
  brace-style:
    - error
    - 1tbs
    - allowSingleLine: true
  spaced-comment: off
  camelcase: off #The 2600Hz Javascript Style Guide states that variable names should be camel case. However, snake case is sometimes required in the existing code.
  no-unneeded-ternary: off
  eqeqeq: error #May need to turn "off" due to intentional use of "==" and "!=" in some files
  no-unused-vars:
    - error
    - {
      #Allow unused variable if they are requires or self-references as they are useful in future. Also allow charts because they are used globally but linter can't pick up on that.
      varsIgnorePattern:
        "_|self|toastr|.*[cC]hart",
      #Allow arguments called status or data to be unused (They are required as arguments to the callbacks provided to monster#request()
        argsIgnorePattern:
        "status|_status|data|_data|e"
      }
  operator-linebreak: 
    - error
    - before
  #Deprecated rule.
  no-native-reassign: off
  no-extend-native: off
  no-new-object: error
  no-array-constructor: error
  quotes:
    - error
    - single
  quote-props:
    - warn
    - as-needed
    - {
        keywords: true,
        unnecessary: false
      }
  no-inner-declarations:
    - error
    - both
  dot-notation: error
  vars-on-top: error
  curly:
    - error
    - all
  space-infix-ops:
    - error
  comma-style:
    - error
    - last
  comma-dangle:
    - error
    - never
  id-length:
    - warn
    - {
        exceptions: ["$", "_", "e"]
      }
### GIT-DEPENDENT RULES ###
#Depending on your git settings, these rules may not apply, as git could automatically be enforcing them.
#Only enable these rules if git is configured to commit as-is, or if you are otherwise sure you need to use them.
  linebreak-style:
    - error
    - windows
  eol-last:
    - error
    - always
